services:
  postgres-sql:
    image: postgres:16-alpine
    container_name: postgres-sql

  mongodb:
    image: mongo:7.0
    container_name: mongodb

  redis:
    image: redis:7.0-alpine
    container_name: redis

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog_api
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog/Api/Catalog.Api/Dockerfile

# Volumes are now mapped to docker-volumes folder via docker-compose.override.yml
